### ISSUE TITLE
Typo in Conditional Kernel code for da_experiments ?

### ISSUE THREAD

**Issue by vpellegrain** [g-pichler/knife#2]
Hi,

I'm currently playing your KNIFE estimator, and I wonder if there is a typo or not in the computation of the log_pdf of the Conditional Kernel:

If I understand correctly, in the forward pass (or learning loss) of KNIFE estimator, we want to estimate both p(z_d) and p(z_d | z_c).
For p(z_d | z_c) we thus use the `CondKernel` class, in which the conditional density p(z_d | z_c) is estimated by using different FF layers to compute means, logvar, etc. from z_c samples.

Hence, I think that the initialization steps of these layers carry some typos w.r.t. the dimensions:
 
`self.mu = FF(args, self.d, self.d, self.K * self.d) `
`self.logvar = FF(args, self.d, self.d, self.K * self.d)`
`self.weight = FF(args, self.d, self.d, self.K)`
`self.tri = FF(args, self.d, self.d, self.K * self.d * self.d)`

with `self.d = zd_dim`

If we suppose now that we have different dimensions for z_c and z_d, i guess that the input dimension of these layers should rather be `zc_dim`, if I'm not wrong ?

Thank you in advance for your answer.

**Comment by mboudiaf** [comment]
HI @vpellegrain 

Indeed you're right. I think I missed that because we always use the same dimensions for z_c and z_d, but the code would have crashed otherwise. Thanks for raising, I should have fixed that :)

**Comment by g-pichler** [comment]
Ok. Then time to close this ;)
