### ISSUE TITLE
Dev set or test set?

### ISSUE THREAD

**Issue by qfkkwgd** [g-pichler/knife#3]
I have a question about the table 2 in your paper. You mentioned in the "setup" section that your model was evaluated on the dev set of GLUE following VIBERT. However, in their paper section 3.1, they mentioned their results are obtained from GLUE test set. So I wonder on which split you did the experiments for Table 2, dev or test.

**Comment by PierreColombo** [comment]
Hi,

Thanks for the question.

This is done on validation (https://github.com/g-pichler/knife/blob/master/text_experiments/fine_tuning/train.py see l 733)

Same as here : https://github.com/rabeehk/vibert/blob/master/run_glue.py see l404.

Hope it helps.
